var searchData=
[
  ['makeptr',['makePtr',['../namespacetgbot_1_1utils.html#a6ff275dfd86bb47d723c6ee372e96320',1,'tgbot::utils']]],
  ['maskposition',['MaskPosition',['../structtgbot_1_1types_1_1MaskPosition.html',1,'tgbot::types']]],
  ['matchercallback',['MatcherCallback',['../namespacetgbot.html#ad2eebb60e276a5062d9f38eca77f7631',1,'tgbot']]],
  ['message',['Message',['../structtgbot_1_1types_1_1Message.html',1,'tgbot::types']]],
  ['messageentity',['MessageEntity',['../structtgbot_1_1types_1_1MessageEntity.html',1,'tgbot::types']]],
  ['multipartupload',['multiPartUpload',['../namespacetgbot_1_1utils_1_1http.html#a9ab93111b505e8e77b309c8ed3d45842',1,'tgbot::utils::http::multiPartUpload(CURL *c, const std::string &amp;operation, const std::string &amp;chatId, const std::string &amp;mimeType, const std::string &amp;type, const std::string &amp;filename)'],['../namespacetgbot_1_1utils_1_1http.html#a778d4ffb7f9dd77e62a2e24732b45253',1,'tgbot::utils::http::multiPartUpload(CURL *c, const std::string &amp;operation, const std::string &amp;cert, const std::string &amp;url, const int &amp;maxConn, const std::string &amp;allowedUpdates=&quot;&quot;)'],['../namespacetgbot_1_1utils_1_1http.html#a079b79b9e68e108f601bc7364824b424',1,'tgbot::utils::http::multiPartUpload(CURL *c, const std::string &amp;operation, const int &amp;userId, const std::string &amp;filename)'],['../namespacetgbot_1_1utils_1_1http.html#a2dc743e077989e03e6718dc04df3a9eb',1,'tgbot::utils::http::multiPartUpload(CURL *c, const std::string &amp;operation, const int &amp;userId, const std::string &amp;name, const std::string &amp;emoji, const std::string &amp;filename, const std::string &amp;title)'],['../namespacetgbot_1_1utils_1_1http.html#aaadb11311a511f696b0343fb7b904c37',1,'tgbot::utils::http::multiPartUpload(CURL *c, const std::string &amp;operation, const int &amp;userId, const std::string &amp;name, const std::string &amp;emoji, const std::string &amp;serializedMaskPosition, const std::string &amp;filename, const std::string &amp;title)']]]
];
